input_basedir: "."

input:
  - name: "accommodation"
  - name: "administration"
  - name: "amenity"
  - name: "barrier"
  - name: "eat-drink"
  - name: "emergency"
  - name: "energy"
  - name: "health"
  - name: "money"
  - name: "nature"
  - name: "outdoor"
  - name: "religious"
  - name: "shop"
  - name: "sports"
  - name: "tourism"
  - name: "transport"

output_basedir: "export"
# WARNING: deletes all files within output directory if it exists
empty_output: true
format: "png"
retina: true
subdirs: false

global_style:
  padding: 1
  fill: "#1a1a1a"

  halo:
    fill: "#ffffff"
    width: 1
    opacity: 0.3
