# This is a basic workflow to help you get started with Actions

name: Build Navit

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults: &defaults
    runs-on: ubuntu-latest
jobs:
  sanity_check:
    runs-on: ubuntu-latest
    container:
        image: navit/sanity_check:latest
    steps:
        - uses: actions/checkout@v2
        - name: run sanity check script
          run: bash scripts/ci_sanity_checks.sh
        - name: Run CheckStyle Test
          run: ./gradlew checkstyleMain
        - uses: actions/upload-artifact@v1
          with:
            name: Store checkstyle report
            path: navit/android/checkstyle
  build_linux:
    <<: *defaults
    needs: sanity_check
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update && apt-get install -y git
      - name: Setup requirements
        run: |
           bash scripts/setup_common_requirements.sh
           apt-get install -y libpng-dev libfreetype6-dev libdbus-glib-1-dev libgtk2.0-dev curl
      - name: Build for Linux
        run: bash scripts/build_linux.sh
      - uses: actions/upload-artifact@v1
        with:
           path: linux/_CPack_Packages
      - name: Update Navit-Download-Center
        run: |
            bash scripts/update_download_center.sh
  run_doxygen:
    <<: *defaults
    needs: [build_android, build_wince, build_tomtom_minimal, build_linux, build_tomtom_plugin, build_win32]
    steps:
      - uses: actions/checkout@v2
      - name: Install doxygen and other essentials
        run: apt-get update && apt-get -y install doxygen ca-certificates git rsync
      - name: Run doxygen
        run: cd navit && doxygen
      - name: Update results to Github
        run: bash scripts/update_doxygen.sh
      - uses: actions/upload-artifact@v1
        with:
          path: /root/project/doc
  build_sailfish:
    <<: *defaults
    needs: sanity_check
    container:
        image: jkoan/test:sailfish
    steps:
      - uses: actions/checkout@v2
      # TODO currently broken because of USER in Dockerimage and probably because of double containers as well
      #- name: run build
      #  run: contrib/sailfish/build_sailfish_ci.sh
      #  env:
      #      VERSION_ID: 3.1.0.12
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: Store rpm
      #    path: rpmbuild/RPMS/
  build_android:
    <<: *defaults
    needs: sanity_check
    container:
        image: jkoan/test
    env:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      KEYSTORE: '/home/circleci/.keystore'
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: scripts/setup_android.sh
      - name: Setup Keystore and Playstore Keys
        run: scripts/setup_publish_keys.sh
      - name: Build and upload Android
        run: fastlane circleci
      - name: Run Lint Test
        run: |
            ln -sf navit/navit.dtd navit.dtd
            mkdir test-results
            ./gradlew lint test
      - name: Run Javadoc
        run: ./gradlew generateDebugJavadoc
      - uses: actions/upload-artifact@v1
        with:
          name: Store APK
          path: navit/android/build/outputs/apk
      - uses: actions/upload-artifact@v1
        with:
          name: Store logs
          path: navit/android/build/outputs/logs
      - uses: actions/upload-artifact@v1
        with:
          name: Store Javadoc
          path: navit/android/build/outputs/docs/javadoc
      - uses: actions/upload-artifact@v1
        with:
          name: Store Lint reports
          path: navit/android/build/reports
      - uses: actions/upload-artifact@v1
        with:
          path: test-results
      - name: Update Navit-Download-Center
        run: |
            bash scripts/update_download_center.sh
  build_win32:
    <<: *defaults
    needs: sanity_check
    container:
        image: ubuntu:16.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update && apt-get install -y git
      - name: Prepare the Windows build environment
        run: |
            apt-get update && xargs -a scripts/setup_14.04_requirements.list apt-get install -y
            apt-get install -y software-properties-common
            add-apt-repository -y ppa:george-edison55/cmake-3.x
            apt-get install -y cmake mingw-w64 mingw-w64-tools default-jdk nsis libsaxonb-java curl
      - name: Build for Windows
        run: |
            bash scripts/build_win32.sh
      - uses: actions/upload-artifact@v1
        with:
          path: win32/navit.exe
      - name: Update Navit-Download-Center
        run: |
            bash scripts/update_download_center.sh
  build_wince:
    <<: *defaults
    needs: sanity_check
    container:
        image: navit/dockerfiles:wince
    steps:
      - uses: actions/checkout@v2
      - run: |
          apt-get update && apt-get install -y git-core
      - name: Prepare the WinCE build environment
        run: |
            bash scripts/setup_wince.sh
      - name: Build for Windows CE
        run: bash scripts/build_wince.sh
      - uses: actions/upload-artifact@v1
        with:
          path: wince/output
      - name: Update Navit-Download-Center
        run: |
            bash scripts/update_download_center.sh
  build_tomtom_minimal:
    needs: sanity_check
    container:
        image: navit/tomtom-ng
    steps:
      - uses: actions/checkout@v2
      - name: Prepare the tomtom build environment
        run: |
            bash scripts/setup_common_requirements.sh
            apt-get install -y xsltproc
      - name: Build for Tomtom (minimal)
        run: bash scripts/build_tomtom_minimal.sh
      - uses: actions/upload-artifact@v1
        with:
          path: /output
      - name: Update Navit-Download-Center
        run: |
            bash scripts/update_download_center.sh
  build_tomtom_plugin:
    <<: *defaults
    needs: sanity_check
    container:
        image: navit/tomtom-ng
    steps:
      - uses: actions/checkout@v2
      - name: Prepare the tomtom build environment
        run: |
            bash scripts/setup_common_requirements.sh
            apt-get install -y xsltproc
      - name: Build for Tomtom (plugin)
        run: |
            bash scripts/build_tomtom_plugin.sh
      - uses: actions/upload-artifact@v1
        with:
          path: /output
      - name: Update Navit-Download-Center
        run: |
            bash scripts/update_download_center.sh
  merge_trunk_in_master:
    <<: *defaults
    needs: [build_android, build_wince, build_tomtom_minimal, build_linux, build_tomtom_plugin, build_win32]
    if: github.ref == 'trunk'
    steps:
      - uses: actions/checkout@master
      - name: Merge to master branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

